{
 "title": "Test Service Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current response time [1m]",
   "type": "stat",
   "description": "Calculated using the last 2 values in 1 minute range",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(test_service_response_time_seconds_sum{job=\"spring-app\"}[1m])/irate(test_service_response_time_seconds_count{job=\"spring-app\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current response time [1m]",
   "type": "timeseries",
   "description": "Each data point is calculated over 1 minute range",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(test_service_response_time_seconds_sum{job=\"spring-app\"}[1m])/irate(test_service_response_time_seconds_count{job=\"spring-app\"}[1m])",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Current average response time [1m]",
   "type": "stat",
   "description": "Calculated over 1 minute range",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(test_service_response_time_seconds_sum{job=\"spring-app\"}[1m])/rate(test_service_response_time_seconds_count{job=\"spring-app\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current response time [1m]",
   "type": "timeseries",
   "description": "Each data point is calculated over 1 minute range",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(test_service_response_time_seconds_sum{job=\"spring-app\"}[1m])/rate(test_service_response_time_seconds_count{job=\"spring-app\"}[1m])",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Response Time Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.25, test_service_response_time_seconds_bucket{job=\"spring-app\"})",
     "legendFormat": "0.25"
    },
    {
     "expr": "histogram_quantile(0.5, test_service_response_time_seconds_bucket{job=\"spring-app\"})",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.75, test_service_response_time_seconds_bucket{job=\"spring-app\"})",
     "legendFormat": "0.75"
    }
   ]
  },
  {
   "title": "Current response time (s) histogram at ${__to:date:YYYY-MM-DD HH:mm}",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "observations" } },
   "targets": [
    {
     "expr": "test_service_response_time_seconds_bucket{job=\"spring-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Test Service Response time seconds",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "test_service_response_time_seconds_bucket{job=\"spring-app\"}",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}